apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-api
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
  egress:
    - ports:
        - port: 5432
        - port: 6379
        - port: 443
        - port: 53
          protocol: UDP
